#!/usr/bin/env bash

## Copyright (c) 2017 helmuthdu <helmuthdu@gmail.com>
## Copyright (c) 2018 Stephen Ribich <stephen.ribich@gmail.com>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

################################################################################## Message Attributes
################################################################################

FONT_BOLD="$(tput bold)"
FONT_RESET="$(tput sgr0)"

# Colors
FONT_RED="$(tput setaf 1)"
FONT_GREEN="$(tput setaf 2)"
FONT_YELLOW="$(tput setaf 3)"
FONT_BLUE="$(tput setaf 4)"
FONT_PURPLE="$(tput setaf 5)"
FONT_CYAN="$(tput setaf 6)"
FONT_WHITE="$(tput setaf 7)"

# Bold Colors
FONT_BRED="${FONT_BOLD}${FONT_RED}"
FONT_BGREEN="${FONT_BOLD}${FONT_GREEN}"
FONT_BYELLOW="${FONT_BOLD}${FONT_YELLOW}"
FONT_BBLUE="${FONT_BOLD}${FONT_BLUE}"
FONT_BPURPLE="${FONT_BOLD}${FONT_PURPLE}"
FONT_BCYAN="${FONT_BOLD}${FONT_CYAN}"
FONT_BWHITE="${FONT_BOLD}${FONT_WHITE}"

# Prompts


################################################################################## Terminal Normalization
################################################################################

## Set the console width to the maximum available to the terminal.
##
set_columns()
{
    COLUMNS="$(tput cols)"
}







################################################################################
## Message Types
################################################################################



