#!/usr/bin/env bash

declare -x EDITOR=""

select_editor()
{
  local -a editor_list=("vi" "vim" "nano")

  print_title "EDITOR - Editor Configuration"

  selection "Select editor" \
            "${editor_list[@]}"

  EDITOR="${SELECTION_VALUE}"
}
