#!/usr/bin/env bash

declare -x EDITOR=""

select_editor()
{
  local -a editor_list=("vi" "vim" "nano")

  print.title "EDITOR - Editor Configuration"

  selection.create "EDITOR" "Select editor" "${editor_list[@]}"
}
