#!/usr/bin/env bash

declare ROOT_PASSWORD_STATUS=""

configure_root_password()
{
    print.title "Configure Root Password"
    print.info  "Enter your new root password"

    arch_chroot "passwd"

    ROOT_PASSWORD_STATUS="${FONT_OK}"
}
