#!/usr/bin/env bash

configure_mkinitcpio()
{
    print.title "MKINITCPIO - CONFIGURE MKINITCPIO"
    print.info  "Create the initial ramdisk environment."

    # IF LUKS
    # [[ $LUKS -eq 1 ]] && sed -i '/^HOOK/s/block/block keymap encrypt/' ${MOUNTPOINT}/etc/mkinitcpio.conf
    # [[ $LVM -eq 1 ]] && sed -i '/^HOOK/s/filesystems/lvm2 filesystems/' ${MOUNTPOINT}/etc/mkinitcpio.conf

    if [ "$(arch-chroot "ls /boot" | grep hardened -c)" -gt "0" ]; then
        arch_chroot "mkinitcpio -p linux-hardened"
    elif [ "$(arch-chroot "ls /boot" | grep lts -c)" -gt "0" ]; then
        arch_chroot "mkinitcpio -p linux-lts"
    else
        arch_chroot "mkinitcpio -p linux"
    fi
}
