#!/usr/bin/env bash
# module

run()
{
    local length="${#}"
    local items=()

    local init=""

    if [[ $((length % 2)) -ne 0 ]]; then
        init="$1"
        shift
    fi

    length=$((length / 2))

    i=0
    while [[ "${#}" -ne 0 ]]; do
        varname="menu_${i}_${RANDOM}"

        items["${i}"]="$varname"

        eval "local ${varname}=('${1}' '${2}' 0)"

        i=$((i + 1))
        shift
        shift
    done

    while :; do
        if [[ -n "$init" ]]; then
            "$init"
        fi

        for i in $(seq 1 "${length}"); do
            local arr="${!items[$(( i - 1 )]}"

            printf " %i) %s\n" "${i}" "test"
            # $(menu.item '${arr[2]}' '${arr[0]} ${!arr[1]}')
        done

        printf " d) done\n"

    done
}
