#!/usr/bin/env bash
# module

run()
{
    local length="${#}"
    local items=()

    local init=""

    if [[ $((length % 2)) -ne 0 ]]; then
        init="$1"
        shift
    fi

    length=$((length / 2))

    i=0
    while [[ "${#}" -ne 0 ]]; do
        varname="menu_${i}_${RANDOM}"

        items["${i}"]="$varname"

        eval "local ${varname}=('${1}' '${2}' 0)"

        i=$((i + 1))
        shift
        shift
    done

    while :; do
        if [[ -n "$init" ]]; then
            "$init"
        fi

        for i in $(seq 1 "${length}"); do
            local arr="${items[$(( i - 1 ))]}"
            declare -n list="$arr"

            printf " %i) %s\n" "${i}" "$(menu.item "${list[2]}" "${list[0]}" "${list[1]}")"
        done

        printf " d) done\n"

        exit 1
    done
}







checklist=(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)

show_menu()
{
    printf " 1) %s\n" "$(mainmenu_item                  \
                             "${checklist[1]}"          \
                             "Select Keymap"            \
                             "${KEYMAP}")"
    printf " 2) %s\n" "$(mainmenu_item                  \
                             "${checklist[2]}"          \
                             "Select Editor"            \
                             "${EDITOR}")"
}

_menu()
{


    printf " 3) %s\n" "$(mainmenu_item                  \
                             "${checklist[3]}"          \
                             "Partition Disk"           \
                             "")"
    printf " 4) %s\n" "$(mainmenu_item                  \
                             "${checklist[4]}"          \
                             "Install Base System"      \
                             "")"
    printf " 5) %s\n" "$(mainmenu_item                  \
                             "${checklist[5]}"          \
                             "Configure Fstab"          \
                             "")"
    printf " 6) %s\n" "$(mainmenu_item                  \
                             "${checklist[6]}"          \
                             "Configure Hostname"       \
                             "")"
    printf " 7) %s\n" "$(mainmenu_item                  \
                             "${checklist[7]}"          \
                             "Configure Timezone"       \
                             "")"
    printf " 8) %s\n" "$(mainmenu_item                  \
                             "${checklist[8]}"          \
                             "Configure Hardware Clock" \
                             "")"
    printf " 9) %s\n" "$(mainmenu_item                  \
                             "${checklist[9]}"          \
                             "Configure Locale"         \
                             "")"
    printf "10) %s\n" "$(mainmenu_item                  \
                             "${checklist[10]}"         \
                             "Configure Mkinitcpio"     \
                             "")"
    printf "11) %s\n" "$(mainmenu_item                  \
                             "${checklist[11]}"         \
                             "Install Bootloader"       \
                             "")"
    printf "12) %s\n" "$(mainmenu_item                  \
                             "${checklist[12]}"         \
                             "Configure Root Password"  \
                             "")"

    printf "\n"
    printf " d) %s\n" "Done"
    printf "\n"
}

print_options()
{
    local option

    read -r -p "Enter your selection: " option

    case "${option}" in
        1)
            select_keymap
            checklist[1]=1
            ;;
        2)
            select_editor
            checklist[2]=1
            ;;
        3)
            partition_disk
            checklist[3]=1
            ;;
        4)
            install_base_system
            configure_keymap
            configure_dns
            checklist[4]=1
            ;;
        5)
            configure_fstab
            checklist[5]=1
            ;;
        11)
            install_bootloader
            checklist[11]=1
            ;;
        12)
            configure_root_password
            checklist[12]=1
            ;;
        d)
            finish
            ;;
        *)
            invalid_option
            ;;
    esac
}

## Print a checkbox
##
checkbox()
{
    if [[ "${1}" -eq 1 ]]; then
        printf "%s[%s%sx%s%s]%s\n" \
               "${FONT_BBLUE}"   \
               "${FONT_RESET}"   \
               "${FONT_BOLD}"    \
               "${FONT_RESET}"   \
               "${FONT_BBLUE}"   \
               "${FONT_RESET}"
    else
        printf "%s[ ]%s\n" "${FONT_BBLUE}" "${FONT_RESET}"
    fi
}

## Print a menu item in the following format:
##   [ ] text [state]
##
item()
{
    local state=""

    if [[ "$1" -eq 1 && "$3" != "" ]]; then
        state="${FONT_BGREEN}[${FONT_RESET}${3}${FONT_BGREEN}]${FONT_RESET}"
    fi

    printf "%s %s%s%s %s"     \
           "$(menu.checkbox "$1")" \
           "${FONT_BOLD}"     \
           "${2}"             \
           "${FONT_RESET}"    \
           "${state}"
}
