#!/usr/bin/env bash
## Copyright (c) 2017 Stephen Ribich
##
## Permission is hereby granted, free of charge, to any person obtaining a copy
## of this software and associated documentation files (the "Software"), to deal
## in the Software without restriction, including without limitation the rights
## to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
## copies of the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included in
## all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
## AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
## OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
## SOFTWARE.

# shellcheck disable=2034

# Attributes
FONT_BOLD="$(tput bold)"
FONT_RESET="$(tput sgr0)"

# Colors
FONT_RED="$(tput setaf 1)"
FONT_GREEN="$(tput setaf 2)"
FONT_YELLOW="$(tput setaf 3)"
FONT_BLUE="$(tput setaf 4)"
FONT_PURPLE="$(tput setaf 5)"
FONT_CYAN="$(tput setaf 6)"
FONT_WHITE="$(tput setaf 7)"

# Bold Colors
FONT_BRED="${_BOLD}${_RED}"
FONT_BGREEN="${_BOLD}${_GREEN}"
FONT_BYELLOW="${_BOLD}${_YELLOW}"
FONT_BBLUE="${_BOLD}${_BLUE}"
FONT_BPURPLE="${_BOLD}${_PURPLE}"
FONT_BCYAN="${_BOLD}${_CYAN}"
FONT_BWHITE="${_BOLD}${_WHITE}"

# Prompts
SELECTION_PROMPT="Enter your selection: "

## Print a horizontal rule of the character "-"
##
print_line()
{
  printf "%$(tput cols)s\n" | tr ' ' '-'
}

## Print a header on the top of the terminal. This clears the terminal to easily
## get a position on the top of the terminal
##
print_title()
{
  clear
  print_line
  printf "%s%s%s\n" "${FONT_BOLD}" "${1}" "${FONT_RESET}"
  print_line
  printf "\n"
}

## Print a general message to the terminal
##
print_info()
{
  printf "%s%s%s\n\n" "${FONT_BOLD}" "${1}" "${FONT_RESET}" \
    | fold -sw "$(tput cols)"
}

## Print a yellow warning message to the terminal
##
print_warning()
{
  printf "%s%s%s\n" "${FONT_BYELLOW}" "${1}" "${FONT_RESET}" \
    | fold -sw "$(tput cols)"
}
