#!/usr/bin/env bash
## Copyright (c) 2017 helmuthdu <helmuthdu@gmail.com>
## Copyright (c) 2017 Stephen Ribich <stephen.ribich@gmail.com>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

export declare -- KEYMAP

## Set the system locale and keyboard layout settings for both the virtual
## console and Xorg using the localectl tool
##
## https://wiki.archlinux.org/index.php/keymap
##
select_keymap()
{
    local -- title="KEYMAP - Keyboard Configuration"
    local -- info="Set the system locale and keyboard layout settings for the virtual console and Xorg using the localectl tool"

    local -a keymap_list

    keymap_list=( $(localectl list-keymaps | tr '\n' ' ') )

    print_title "${title}"
    print_info "${info}"

    set_columns
    set_prompt

    select KEYMAP in "${keymap_list[@]}"; do
        if contains_element keymap_list "${KEYMAP}"; then
            localectl set-keymap --no-convert "${KEYMAP}"
            break
        else
            invalid_option

            print_title "${title}"
            print_info "${info}"
        fi
    done
}
