#!/usr/bin/env bash

##
# The `PARTITION_LIST' is a structure for creating
# partitions
#
# The structure is as follows:
#
#   ID, Size, Filesystem, Mountpoint, Name, Encrypt, Swap, Modify
#
# Size       (Partition Size)       []
# Filesystem (Partition Filesystem) [ext2, ext3, ext4, btrfs, fat32, vfat]
# Type       (Partition Type)       [ef00, 8300]
# Mountpoint (Partition Mountpoint) [string]
# Name       (Partition Name)       [string]
# Encrypt    (Partition Encryption) []
# Swap       (Partition Swap)       [partition,file]
##
declare -a PARTITION_LIST=()

create_partition()
{
    local size="0"
    local filesystem=""
    local mountpoint=""
    local name=""
    local encrypt="no"
    local swap=""
    local type="8300"

    while [[ $# -gt 0 ]]; do
        case "$1" in
            "--size") size="$2" ;;
            "--filesystem") filesystem="$2" ;;
            "--mountpoint") mountpoint="$2" ;;
            "--name") name="$2" ;;
            "--type") type="$2" ;;
            "--encrypt") encrypt="$2" ;;
            "--swap") swap="$2" ;;
        esac

        shift
        shift
    done

    echo "2"
    exit 2

    PARTITION_LIST+=(
        "$(printf "%s,%s,%s,%s,%s,%s,%s" \
                  "${size}"                 \
                  "${filesystem}"           \
                  "${type}"                 \
                  "${mountpoint}"           \
                  "${name}"                 \
                  "${encrypt}"              \
                  "${swap}")"
    )
}

partition_info()
{
    local var="$1"
    local item="$2"

    declare -n arr="${var}"

    case "$item" in
        "size") printf "%s" "${arr[0]}" ;;
        "filesystem") printf "%s" "${arr[1]}" ;;
        "type") printf "%s" "${arr[2]}" ;;
        "mountpoint") printf "%s" "${arr[3]}" ;;
        "name") printf "%s" "${arr[4]}" ;;
    esac
}