#!/usr/bin/env bash

## Copyright (c) 2017 helmuthdu <helmuthdu@gmail.com>
## Copyright (c) 2017 Stephen Ribich <stephen.ribich@gmail.com>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

## Pause the execution of the script and wait for user input.
##
pause_function()
{
    print_line

    if [[ "${#}" -gt 0 ]]; then
        printf "%s\n" "${1}"
    fi

    read -r -e -sn 1 -p "Press enter to continue..."
    printf "\033[1A\r\033[K\033[1A\r\033[K"
}

## Pause script execution and notify the user that an invalid option has
## been selected.
##
invalid_option()
{
    pause_function "Invalid option. Try again"
}



##
##
ifndev()
{
    if [[ "${DEVELOPMENT}" -eq 1 ]]; then
        return 0
    fi

    if [[ "$#" -gt 0 ]]; then
        "$@"
        return "$?"
    fi

    return 0
}
