#!/usr/bin/env bash
## Copyright (c) 2017 helmuthdu <helmuthdu@gmail.com>
## Copyright (c) 2017 Stephen Ribich <stephen.ribich@gmail.com>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Attributes
FONT_BOLD="$(tput bold)"
FONT_RESET="$(tput sgr0)"

# Colors
FONT_RED="$(tput setaf 1)"
FONT_GREEN="$(tput setaf 2)"
FONT_YELLOW="$(tput setaf 3)"
FONT_BLUE="$(tput setaf 4)"
FONT_PURPLE="$(tput setaf 5)"
FONT_CYAN="$(tput setaf 6)"
FONT_WHITE="$(tput setaf 7)"

# Bold Colors
FONT_BRED="${_BOLD}${_RED}"
FONT_BGREEN="${_BOLD}${_GREEN}"
FONT_BYELLOW="${FONT_BOLD}${FONT_YELLOW}"
FONT_BBLUE="${_BOLD}${_BLUE}"
FONT_BPURPLE="${_BOLD}${_PURPLE}"
FONT_BCYAN="${_BOLD}${_CYAN}"
FONT_BWHITE="${_BOLD}${_WHITE}"

# Prompts
SELECTION_PROMPT="Enter your selection: "

## Print a horizontal rule of the character "-"
##
print_line()
{
    printf "%$(tput cols)s\n" | tr ' ' '-'
}

## Print a header on the top of the terminal. This clears the terminal to easily
## get a position on the top of the terminal
##
print_title()
{
    clear
    print_line
    printf "%s%s%s\n" "${FONT_BOLD}" "${1}" "${FONT_RESET}"
    print_line
    printf "\n"
}

## Print a general message to the terminal
##
print_info()
{
    printf "%s%s%s\n\n" "${FONT_BOLD}" "${1}" "${FONT_RESET}" \
        | fold -sw "$(tput cols)"
}

## Print a yellow warning message to the terminal
##
print_warning()
{
    printf "%s%s%s\n" "${FONT_BYELLOW}" "${1}" "${FONT_RESET}" \
        | fold -sw "$(tput cols)"
}
