#!/usr/bin/env bash
## Copyright (c) 2017 helmuthdu <helmuthdu@gmail.com>
## Copyright (c) 2017 Stephen Ribich <stephen.ribich@gmail.com>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

SELECTION_VALUE=""

selection()
{
    local title=""
    local value="1"
    local length=""

    title="$1"; shift
    length="$#"

    printf "%s%s%s\n\n" "${FONT_BOLD}" "${title}" "${FONT_RESET}"

    _selection_print "0" "${value}" "${@}"

    while read -rsn1 key; do
        case "${key}" in
            $'\x1b')
                read -rsn1 -t 0.1 tmp
                if [[ "${tmp}" == "[" ]]; then
                    read -rsn1 -t 0.1 tmp
                    case "${tmp}" in
                        "A") # Up
                            if [[ "${value}" -eq 1 ]]; then
                                value="${length}"
                            else
                                value="$(( value - 1 ))"
                            fi
                            ;;
                        "B") #Down
                            if [[ "${value}" -eq "${length}" ]]; then
                                value="1"
                            else
                                value="$(( value + 1 ))"
                            fi
                            ;;
                    esac
                fi
                ;;
            "")
                break
                ;;
        esac

        _selection_print "1" "${value}" "$@"
    done

    _selection_clear "${length}"

    SELECTION_VALUE="${!value}"
}

selection_value()
{
    if [[ "$1" == "${SELECTION_VALUE}" ]]; then
        return 0
    fi

    return 1
}

_selection_print()
{
    local list_id=1
    local list_age="$1"; shift
    local list_selected="$1"; shift

    if [[ "${list_age}" -ne 0 ]]; then
        printf "\033[%iA" "$#"
    fi

    for item in "$@"; do
        if [[ "${list_id}" == "${list_selected}" ]]; then
            printf "\033[96m"
        fi

        printf "   • %s\n" "${item}"
        printf "\033[0m"
        list_id=$(( list_id + 1 ))
    done
}

_selection_clear()
{
    printf "\033[%iA" "$(( $1 + 1 ))"

    for _ in $(seq 0 "$1"); do
        printf "\r\033[K\n"
    done

    printf "\033[%iA" "$(( $1 + 1 ))"
}
